[package]
name = "lamp"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.11.4", features = ["cuda-version-from-build-system"] }
num = "0.4.3"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
